<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\WorkPhase;

class ProductWorkPhaseSeeder extends Seeder
{

    public function run(): void
    {
        $uploadsPath = public_path('storage/uploads');
        $productsData = [
            'Biolux14.xlsx' => [
                ['Pakovanje poda', 20.0, 1],
                ['Priprema (obrada) stranica I plašta, krajcovanje', 15.0, 1],
                ['Pakovanje I plašt (CO2)', 16.8, 1],
                ['Zavarivanje I plašt (CO2)', 15.0, 1],
                ['Pakovanje sklopa priključaka (sa zadnje strane)', 5.0, 1],
                ['Pakovanje II plašt (CO2)', 105.0, 2],
                ['Zavarivanje II plašt (CO2)', 140.0, 1],
                ['Ispitivanje II plašta', 20.0, 1],
                ['Pakovanje i zavarivanje sklopa kutije primarnog vazduha', 10.0, 1],
                ['Pakovanje i zavarivanje kutije ventilatora (CO2)', 7.0, 1],
                ['Pakovanje turbulatora', 4.2, 1],
                ['Pakovanje, zavarivanje i obrada nosača turbulatora', 16.8, 1],
                ['Kompletiranje turbulatora', 35.0, 1],
                ['Pakovanje silosa', 40.0, 1],
                ['Pakovanje vrata (CO2)', 60.0, 1],
                ['Pakovanje poklopaca (CO2)', 8.0, 1],
                ['Pakovanje, zavarivanje i obrada ložišta', 35.0, 1],
                ['Kićenje I faza (pakovanje i zavarivanje)', 25.0, 1],
                ['Pakovanje i zavarivanje spirale dozera', 14.0, 1],
                ['Pakovanje i zavarivanje osnovnog dela dozera', 10.0, 1],
                ['Ispitivanje II faza', 20.0, 1],
                ['Kićenje I faza završna montaža', 70.0, 1],
                ['Kićenje II faza završna montaža', 168.0, 1],
                ['Završna montaža vrata', 10.0, 1],
                ['Završna montaža poklopca', 12.0, 1],
                ['Pakovanje i varenje oplate (CO2)', 10.0, 1],
                ['Plotna-zavarivanje i obrada', 15.0, 1],
                ['Punktovanje pozicija oplate', 4.0, 1],
                ['Brušenje oplate', 1.0, 1],
                ['Brušenje vrata', 10.0, 1],
                ['Pakovanje i brušenje pepeljare', 15.0, 1],
                ['Kačenje i plasticifiranje oplate', 4.0, 1],
                ['Skidanje sa linije i odlaganje u korpu', 4.0, 1],
                ['Farbanje kotla', 32.0, 1],
                ['Farbanje podsklopova i delova kotla', 32.0, 1],
                ['Sečenje izolacije-priprema izolacije', 14.0, 1],
                ['Priprema oplate za montažu', 70.0, 2],
                ['Završna montaža oplate', 84.0, 2],
                ['Montaža dozera', 25.0, 1],
                ['Priprema elektro podsklopova i programiranje automatike', 32.0, 1],
                ['Montaža elektro podsklopova na proizvod', 32.0, 1],
                ['Test bezbednosti i funkcionalnosti', 13.0, 1],
                ['Pakovanje i priprema kotla za transport', 30.0, 1],
            ],
            'BioluxUNI20.xlsx' => [
                ['Pakovanje poda', 20.0, 1],
                ['Priprema (obrada) stranica I plašta, krajcovanje', 15.0, 1],
                ['Pakovanje I plašt (CO2)', 16.8, 1],
                ['Zavarivanje I plašt (CO2)', 15.0, 1],
                ['Pakovanje sklopa priključaka (sa zadnje strane)', 5.0, 1],
                ['Pakovanje II plašt (CO2)', 105.0, 2],
                ['Zavarivanje II plašt (kutija, ojačanja)', 140.0, 1],
                ['Ispitivanje II plašta', 20.0, 1],
                ['Pakovanje i zavarivanje sklopa kutije primarnog vazduha', 10.0, 1],
                ['Pakovanje i zavarivanje kutije ventilatora (CO2)', 7.0, 1],
                ['Pakovanje turbulatora', 4.2, 1],
                ['Pakovanje, zavarivanje i obrada nosača turbulatora', 16.8, 1],
                ['Kompletiranje turbulatora', 35.0, 1],
                ['Pakovanje silosa', 40.0, 1],
                ['Pakovanje vrata (CO2)', 60.0, 1],
                ['Pakovanje poklopaca (CO2)', 8.0, 1],
                ['Pakovanje, zavarivanje i obrada ložišta', 35.0, 1],
                ['Kićenje I faza (pakovanje i zavarivanje)', 25.0, 1],
                ['Pakovanje i zavarivanje spirale dozera', 14.0, 1],
                ['Pakovanje i zavarivanje osnovnog dela dozera', 10.0, 1],
                ['Ispitivanje II faza', 20.0, 1],
                ['Kićenje I faza završna montaža', 70.0, 1],
                ['Kićenje II faza završna montaža', 168.0, 1],
                ['Završna montaža vrata', 15.0, 1],
                ['Završna montaža poklopca', 12.0, 1],
                ['Pakovanje i varenje oplate (CO2)', 10.0, 1],
                ['Plotna-zavarivanje i obrada', 15.0, 1],
                ['Punktovanje pozicija oplate', 4.0, 1],
                ['Brušenje oplate', 1.0, 1],
                ['Brušenje vrata', 10.0, 1],
                ['Pakovanje i brušenje pepeljare', 15.0, 1],
                ['Kačenje i plasticifiranje oplate', 4.0, 1],
                ['Skidanje sa linije i odlaganje u korpu', 4.0, 1],
                ['Farbanje kotla', 32.0, 1],
                ['Farbanje podsklopova i delova kotla', 32.0, 1],
                ['Sečenje izolacije-priprema izolacije', 14.0, 1],
                ['Priprema oplate za montažu', 70.0, 2],
                ['Završna montaža oplate', 84.0, 2],
                ['Montaža dozera', 25.0, 1],
                ['Priprema elektro podsklopova i programiranje automatike', 32.0, 1],
                ['Montaža elektro podsklopova na proizvod', 32.0, 1],
                ['Test bezbednosti i funkcionalnosti', 13.0, 1],
                ['Pakovanje i priprema kotla za transport', 30.0, 1],
            ],
            'BioluxUNI20+.xlsx' => [
                ['Pakovanje poda', 20.0, 1],
                ['Priprema (obrada) stranica I plašta, krajcovanje', 15.0, 1],
                ['Pakovanje I plašt (CO2)', 16.8, 1],
                ['Zavarivanje I plašt (CO2)', 15.0, 1],
                ['Pakovanje sklopa priključaka (sa zadnje strane)', 5.0, 1],
                ['Pakovanje II plašt (CO2)', 105.0, 2],
                ['Zavarivanje II plašt (CO2)', 140.0, 1],
                ['Ispitivanje II plašta', 20.0, 1],
                ['Pakovanje i zavarivanje sklopa kutije primarnog vazduha', 10.0, 1],
                ['Pakovanje i zavarivanje kutije ventilatora (CO2)', 7.0, 1],
                ['Pakovanje turbulatora', 4.2, 1],
                ['Pakovanje, zavarivanje i obrada nosača turbulatora', 16.8, 1],
                ['Kompletiranje turbulatora', 35.0, 1],
                ['Pakovanje silosa', 40.0, 1],
                ['Pakovanje vrata (CO2)', 60.0, 1],
                ['Pakovanje poklopaca (CO2)', 8.0, 1],
                ['Pakovanje, zavarivanje i obrada ložišta', 35.0, 1],
                ['Kićenje I faza (pakovanje i zavarivanje)', 25.0, 1],
                ['Pakovanje i zavarivanje spirale dozera', 14.0, 1],
                ['Pakovanje i zavarivanje osnovnog dela dozera', 10.0, 1],
                ['Ispitivanje II faza', 20.0, 1],
                ['Kićenje I faza završna montaža', 70.0, 1],
                ['Kićenje II faza završna montaža', 168.0, 1],
                ['Završna montaža vrata', 15.0, 1],
                ['Završna montaža poklopca', 12.0, 1],
                ['Pakovanje i varenje oplate (CO2)', 10.0, 1],
                ['Plotna-zavarivanje i obrada', 15.0, 1],
                ['Punktovanje pozicija oplate', 4.0, 1],
                ['Brušenje oplate', 1.0, 1],
                ['Brušenje vrata', 10.0, 1],
                ['Pakovanje i brušenje pepeljare', 15.0, 1],
                ['Kačenje i plasticifiranje oplate', 4.0, 1],
                ['Skidanje sa linije i odlaganje u korpu', 4.0, 1],
                ['Farbanje kotla', 32.0, 1],
                ['Farbanje podsklopova i delova kotla', 32.0, 1],
                ['Sečenje izolacije-priprema izolacije', 14.0, 1],
                ['Priprema oplate za montažu', 70.0, 2],
                ['Završna montaža oplate', 84.0, 2],
                ['Montaža dozera', 25.0, 1],
                ['Priprema elektro podsklopova i programiranje automatike', 32.0, 1],
                ['Montaža elektro podsklopova na proizvod', 32.0, 1],
                ['Test bezbednosti i funkcionalnosti', 13.0, 1],
                ['Pakovanje i priprema kotla za transport', 30.0, 1],
            ],
            'BioluxUNI25.xlsx' => [
                ['Pakovanje poda', 20.0, 1],
                ['Priprema (obrada) stranica I plašta, krajcovanje', 15.0, 1],
                ['Pakovanje I plašt (CO2)', 16.8, 1],
                ['Zavarivanje I plašt (CO2)', 15.0, 1],
                ['Pakovanje sklopa priključaka (sa zadnje strane)', 5.0, 1],
                ['Pakovanje II plašt (CO2)', 105.0, 2],
                ['Zavarivanje II plašt (CO2)', 140.0, 1],
                ['Ispitivanje II plašta', 20.0, 1],
                ['Pakovanje i zavarivanje sklopa kutije primarnog vazduha', 10.0, 1],
                ['Pakovanje i zavarivanje kutije ventilatora (CO2)', 7.0, 1],
                ['Pakovanje turbulatora', 4.2, 1],
                ['Pakovanje, zavarivanje i obrada nosača turbulatora', 16.8, 1],
                ['Kompletiranje turbulatora', 35.0, 1],
                ['Pakovanje silosa', 40.0, 1],
                ['Pakovanje vrata (CO2)', 60.0, 1],
                ['Pakovanje poklopaca (CO2)', 8.0, 1],
                ['Pakovanje, zavarivanje i obrada ložišta', 35.0, 1],
                ['Kićenje I faza (pakovanje i zavarivanje)', 25.0, 1],
                ['Pakovanje i zavarivanje spirale dozera', 14.0, 1],
                ['Pakovanje i zavarivanje osnovnog dela dozera', 10.0, 1],
                ['Ispitivanje II faza', 20.0, 1],
                ['Kićenje I faza završna montaža', 70.0, 1],
                ['Kićenje II faza završna montaža', 168.0, 1],
                ['Završna montaža vrata', 15.0, 1],
                ['Završna montaža poklopca', 12.0, 1],
                ['Pakovanje i varenje oplate (CO2)', 10.0, 1],
                ['Plotna-zavarivanje i obrada', 15.0, 1],
                ['Punktovanje pozicija oplate', 4.0, 1],
                ['Brušenje oplate', 1.0, 1],
                ['Brušenje vrata', 10.0, 1],
                ['Pakovanje i brušenje pepeljare', 15.0, 1],
                ['Kačenje i plasticifiranje oplate', 4.0, 1],
                ['Skidanje sa linije i odlaganje u korpu', 4.0, 1],
                ['Farbanje kotla', 32.0, 1],
                ['Farbanje podsklopova i delova kotla', 32.0, 1],
                ['Sečenje izolacije-priprema izolacije', 14.0, 1],
                ['Priprema oplate za montažu', 70.0, 2],
                ['Završna montaža oplate', 84.0, 2],
                ['Montaža dozera', 25.0, 1],
                ['Priprema elektro podsklopova i programiranje automatike', 32.0, 1],
                ['Montaža elektro podsklopova na proizvod', 32.0, 1],
                ['Test bezbednosti i funkcionalnosti', 13.0, 1],
                ['Pakovanje i priprema kotla za transport', 30.0, 1],
            ],
            'BioluxUNI25+.xlsx' => [
                ['Pakovanje poda', 20.0, 1],
                ['Priprema (obrada) stranica I plašta, krajcovanje', 15.0, 1],
                ['Pakovanje I plašt (CO2)', 16.8, 1],
                ['Zavarivanje I plašt (CO2)', 15.0, 1],
                ['Pakovanje sklopa priključaka (sa zadnje strane)', 5.0, 1],
                ['Pakovanje II plašt (CO2)', 105.0, 2],
                ['Zavarivanje II plašt (CO2)', 140.0, 1],
                ['Ispitivanje II plašta', 20.0, 1],
                ['Pakovanje i zavarivanje sklopa kutije primarnog vazduha', 10.0, 1],
                ['Pakovanje i zavarivanje kutije ventilatora (CO2)', 7.0, 1],
                ['Pakovanje turbulatora', 4.2, 1],
                ['Pakovanje, zavarivanje i obrada nosača turbulatora', 16.8, 1],
                ['Kompletiranje turbulatora', 35.0, 1],
                ['Pakovanje silosa', 40.0, 1],
                ['Pakovanje vrata (CO2)', 60.0, 1],
                ['Pakovanje poklopaca (CO2)', 8.0, 1],
                ['Pakovanje, zavarivanje i obrada ložišta', 35.0, 1],
                ['Kićenje I faza (pakovanje i zavarivanje)', 25.0, 1],
                ['Pakovanje i zavarivanje spirale dozera', 14.0, 1],
                ['Pakovanje i zavarivanje osnovnog dela dozera', 10.0, 1],
                ['Ispitivanje II faza', 20.0, 1],
                ['Kićenje I faza završna montaža', 70.0, 1],
                ['Kićenje II faza završna montaža', 168.0, 1],
                ['Završna montaža vrata', 15.0, 1],
                ['Završna montaža poklopca', 12.0, 1],
                ['Pakovanje i varenje oplate (CO2)', 10.0, 1],
                ['Plotna-zavarivanje i obrada', 15.0, 1],
                ['Punktovanje pozicija oplate', 4.0, 1],
                ['Brušenje oplate', 1.0, 1],
                ['Brušenje vrata', 10.0, 1],
                ['Pakovanje i brušenje pepeljare', 15.0, 1],
                ['Kačenje i plasticifiranje oplate', 4.0, 1],
                ['Skidanje sa linije i odlaganje u korpu', 4.0, 1],
                ['Farbanje kotla', 32.0, 1],
                ['Farbanje podsklopova i delova kotla', 32.0, 1],
                ['Sečenje izolacije-priprema izolacije', 14.0, 1],
                ['Priprema oplate za montažu', 70.0, 2],
                ['Završna montaža oplate', 84.0, 2],
                ['Montaža dozera', 25.0, 1],
                ['Priprema elektro podsklopova i programiranje automatike', 32.0, 1],
                ['Montaža elektro podsklopova na proizvod', 32.0, 1],
                ['Test bezbednosti i funkcionalnosti', 13.0, 1],
                ['Pakovanje i priprema kotla za transport', 30.0, 1],
            ],
            'Cuba15.xlsx' => [
                ['Pakovanje poda', 20.0, 1],
                ['Priprema (obrada) stranica I plašta, krajcovanje', 15.0, 1],
                ['Pakovanje I plašt (CO2)', 16.8, 1],
                ['Zavarivanje I plašt (CO2)', 15.0, 1],
                ['Pakovanje sklopa priključaka (sa zadnje strane)', 5.0, 1],
                ['Pakovanje II plašt (CO2)', 105.0, 2],
                ['Zavarivanje II plašt (CO2)', 140.0, 1],
                ['Ispitivanje II plašta', 20.0, 1],
                ['Pakovanje i zavarivanje sklopa kutije primarnog vazduha', 10.0, 1],
                ['Pakovanje i zavarivanje kutije ventilatora (CO2)', 7.0, 1],
                ['Pakovanje turbulatora', 4.2, 1],
                ['Pakovanje, zavarivanje i obrada nosača turbulatora', 16.8, 1],
                ['Kompletiranje turbulatora', 35.0, 1],
                ['Pakovanje silosa', 40.0, 1],
                ['Pakovanje vrata (CO2)', 60.0, 1],
                ['Pakovanje poklopaca (CO2)', 8.0, 1],
                ['Pakovanje, zavarivanje i obrada ložišta', 35.0, 1],
                ['Kićenje I faza (pakovanje i zavarivanje)', 25.0, 1],
                ['Pakovanje i zavarivanje spirale dozera', 14.0, 1],
                ['Pakovanje i zavarivanje osnovnog dela dozera', 10.0, 1],
                ['Ispitivanje II faza', 20.0, 1],
                ['Kićenje I faza završna montaža', 70.0, 1],
                ['Kićenje II faza završna montaža', 168.0, 1],
                ['Završna montaža vrata', 10.0, 1],
                ['Završna montaža poklopca', 12.0, 1],
                ['Pakovanje i varenje oplate (CO2)', 10.0, 1],
                ['Plotna-zavarivanje i obrada', 15.0, 1],
                ['Punktovanje pozicija oplate', 4.0, 1],
                ['Brušenje oplate', 1.0, 1],
                ['Brušenje vrata', 10.0, 1],
                ['Pakovanje i brušenje pepeljare', 15.0, 1],
                ['Kačenje i plasticifiranje oplate', 4.0, 1],
                ['Skidanje sa linije i odlaganje u korpu', 4.0, 1],
                ['Farbanje kotla', 32.0, 1],
                ['Farbanje podsklopova i delova kotla', 32.0, 1],
                ['Sečenje izolacije-priprema izolacije', 14.0, 1],
                ['Priprema oplate za montažu', 70.0, 2],
                ['Završna montaža oplate', 84.0, 2],
                ['Montaža dozera', 25.0, 1],
                ['Priprema elektro podsklopova i programiranje automatike', 32.0, 1],
                ['Montaža elektro podsklopova na proizvod', 32.0, 1],
                ['Test bezbednosti i funkcionalnosti', 13.0, 1],
                ['Pakovanje i priprema kotla za transport', 30.0, 1],
            ],
            'Ecoflame.xlsx' => [
                ['Pakovanje varenje vrata', 21, 1],
                ['Pakovanje,zavarivanje i obrada kutije ložišta', 25, 1],
                ['Zavarivanje i obrada poda (CO2)', 10, 1],
                ['Pakovanje i zavarivanje šolje TIG postupkom', 52.5, 1],
                ['Kompletiranje vrata (izolacija i šnjur)', 10, 1],
                ['Kompletiranje poklopaca (izolacija)', 5, 1],
                ['Pakovanje i zavarivanje kutije ventilatora (CO2)', 14, 1],
                ['Pakovanje silosa', 35, 2],
                ['Pakovanje I plašta', 93.33, 2],
                ['Zavarivanje I plašta (CO2)', 60, 1],
                ['Zavarivanje termičkih osiguranja', 8.4, 1],
                ['Pakovanje II plašta', 93.33, 2],
                ['Zavarivanje II plašta (CO2)', 140, 1],
                ['Ispitivanje II plašta', 20, 1],
                ['Pakovanje i zavarivanje mehanizama za čišćenje (CO2)', 20, 1],
                ['Pakovanje turbulatora', 3, 1],
                ['Kompletiranje mehanizma i turbulatora', 15, 1],
                ['Montaža kotla na pod', 10, 1],
                ['Kićenje I faza', 105, 1],
                ['Ispitivanje kotla II faza (završno kićenje)', 20, 1],
                ['Varenje oplate sa pakovanjem', 30, 1],
                ['Brušenje oplate', 25, 1],
                ['Utiskivanje vijaka', 6, 1],
                ['Kačenje', 4, 1],
                ['Plastificiranje', 5, 1],
                ['Skidanje sa linije i odlaganje u korpe', 4, 1],
                ['Farbanje kotla', 35, 1],
                ['Sečenje i postavljanje izolacije na kotao', 5, 3],
                ['Montiranje dozera', 25, 3],
                ['Priprema oplate za montažu', 20, 3],
                ['Montaža elektrokomponenti', 35, 1],
                ['Programiranje automatike', 34, 1],
                ['Završna montaža oplate', 34, 3],
                ['Ispitivanje kotla (test bezbednosti)', 15, 1],
                ['Priprema,pakovanje i zavarivanje dozera (CO2)', 70, 1],
                ['Farbanje delova dozera', 15, 1],
                ['Kompletiranje dozera', 105, 2],
                ['Krajcovanje cevi', 5, 1],
                ['Pakovanje i priprema za transport', 30, 1],
            ],
            'TKAN1.xlsx' => [
                ['Pakovanje veće izm kutije', 10.0, 1],
                ['Pakovanje manje izm kutije', 8.0, 1],
                ['Zavarivanje veće izm kutije na robotu', 4.5, 1],
                ['Zavarivanje manje izm kutije na robotu', 4.5, 1],
                ['Zavarivanje otvora veće izmenjivačke kutije elektrolučno', 5.0, 1],
                ['Zavarivanje otvora veće izmenjivačke kutije (CO2)', 3.0, 1],
                ['Zavarivanje otvora manje izmenjivačke kutije Elektrolučno', 3.0, 1],
                ['Zavarivanje otvora manje izmenjivačke kutije (CO2)', 2.0, 1],
                ['Pakovanje i krajcovanje dimnjače', 10.0, 1],
                ['Zavarivanje dimnjače', 3.0, 1],
                ['Pakovanje i krajcovanje gornjeg okvira vrata', 8.0, 1],
                ['Zavarivanje gornjeg okvira vrata', 3.0, 1],
                ['Pakovanje I plašta', 130.0, 1],
                ['Zavarivanje I plašta', 110.0, 1],
                ['Zavarivanje I plašta na robotu', 80.0, 1],
                ['Zavarivanje II plašta na robotu', 90.0, 1],
                ['Pakovanje II plašta', 210.0, 1],
                ['Zavarivanje II plašta', 90.0, 1],
                ['Pakovanje poda I faza', 12.0, 1],
                ['Pakovanje poda II faza', 25.0, 1],
                ['Zavarivanje poda', 50.0, 1],
                ['Obrada poda', 15.0, 1],
                ['Betoniranje poda', 40.0, 1],
                ['Kićenje', 140.0, 1],
                ['Zavarivanje vazdušnih kanala', 20.0, 1],
                ['Farbanje kotla', 50.0, 1],
                ['Postavljanje zaštitnog lima', 10.0, 1],
                ['Pakovanje nosača rosta', 5.0, 1],
                ['Zavarivanje nosača rosta', 5.0, 1],
                ['Pakovanje turbulatora', 7.0, 1],
                ['Zavarivanje turbulatora', 4.0, 1],
                ['Pakovanje bočnog poklopca ložišta (za beton)', 4.0, 1],
                ['Zavarivanje bočnog poklopca ložišta', 3.0, 1],
                ['Pakovanje,zavarivanje i obrada pepeljare', 15.0, 1],
                ['Pakovanje i zavarivanje osnovnog lima čančeta', 4.0, 1],
                ['Pakovanje i zavarivanje donjeg sklopa dozera', 50.0, 1],
                ['Pakovanje i zavarivanje gornjeg sklopa dozera', 50.0, 1],
                ['Pakovanje,zavarivanje i obrada kutije lančanika', 20.0, 1],
                ['Zavarivanje i obrada poklopca kutije lančanika', 20.0, 1],
                ['Pakovanje,zavarivanje i obrada zaštite lančanika', 28.0, 1],
                ['Kompletiranje dozera', 140.0, 1],
                ['Farbanje delova dozera', 42.0, 1],
                ['Pakovanje i varenje oplate', 50.0, 1],
                ['Brušenje oplate', 45.0, 1],
                ['Kačenje oplate', 3.0, 1],
                ['Plastificiranje', 4.0, 1],
                ['Skidanje sa linije i odlaganje u korpu', 3.0, 1],
                ['Sečenje izolacije (priprema izolacije)', 20.0, 1],
                ['Lepljenje izolacije na oplatu', 15.0, 1],
                ['Priprema oplate za montažu', 56.0, 2],
                ['Završna montaža oplate', 120.0, 2],
                ['Montaža elektropodsklopova na proizvod', 40.0, 1],
                ['Test bezbednosti i funkcionalnosti', 20.0, 1],
                ['Pakovanje i priprema kotla za transport', 56.0, 1],
            ],
            'TKAN2.xlsx' => [
                ['Pakovanje veće izm kutije', 10.0, 1],
                ['Pakovanje manje izm kutije', 8.0, 1],
                ['Zavarivanje veće izm kutije na robotu', 4.5, 1],
                ['Zavarivanje manje izm kutije na robotu', 4.5, 1],
                ['Zavarivanje otvora veće izmenjivačke kutije elektrolučno', 5.0, 1],
                ['Zavarivanje otvora veće izmenjivačke kutije (CO2)', 3.0, 1],
                ['Zavarivanje otvora manje izmenjivačke kutije Elektrolučno', 3.0, 1],
                ['Zavarivanje otvora manje izmenjivačke kutije (CO2)', 2.0, 1],
                ['Pakovanje i krajcovanje dimnjače', 10.0, 1],
                ['Zavarivanje dimnjače', 3.0, 1],
                ['Pakovanje i krajcovanje gornjeg okvira vrata', 8.0, 1],
                ['Zavarivanje gornjeg okvira vrata', 3.0, 1],
                ['Pakovanje I plašta', 150.0, 2],
                ['Zavarivanje I plašta', 150.0, 1],
                ['Zavarivanje I plašta na robotu', 80.0, 1],
                ['Zavarivanje II plašta na robotu', 90.0, 1],
                ['Pakovanje II plašta', 230.0, 2],
                ['Zavarivanje II plašta', 110.0, 1],
                ['Mokro farbanje vrata', 50.0, 1],
                ['Pakovanje poda I faza', 15.0, 1],
                ['Pakovanje poda II faza', 30.0, 1],
                ['Zavarivanje poda', 60.0, 1],
                ['Obrada poda', 20.0, 1],
                ['Betoniranje poda', 45.0, 1],
                ['Postavljanje zaštitnog lima', 10.0, 1],
                ['Kićenje', 140.0, 1],
                ['Zavarivanje vazdušnih kanala', 20.0, 1],
                ['Spuštanje na pod', 15.0, 1],
                ['Pakovanje nosača rosta', 10.0, 1],
                ['Zavarivanje nosača rosta', 10.0, 1],
                ['Pakovanje turbulatora', 10.0, 1],
                ['Zavarivanje turbulatora', 10.0, 1],
                ['Pakovanje bočnog poklopca ložišta (za beton)', 4.0, 1],
                ['Zavarivanje bočnog poklopca ložišta', 3.0, 1],
                ['Pakovanje,zavarivanje i obrada pepeljare', 20.0, 1],
                ['Pakovanje i zavarivanje gornjeg otvora za čišćenje', 4.0, 1],
                ['Pakovanje i zavarivanje donjeg sklopa dozera', 50.0, 1],
                ['Pakovanje i zavarivanje gornjeg sklopa dozera', 50.0, 1],
                ['Pakovanje,zavarivanje i obrada kutije lančanika', 20.0, 1],
                ['Zavarivanje i obrada poklopca kutije lančanika', 20.0, 1],
                ['Pakovanje,zavarivanje i obrada zaštite lančanika', 28.0, 1],
                ['Kompletiranje dozera', 140.0, 1],
                ['Farbanje delova dozera', 42.0, 1],
                ['Pakovanje i varenje oplate', 50.0, 1],
                ['Brušenje oplate', 45.0, 1],
                ['Kačenje oplate', 3.0, 1],
                ['Plastificiranje', 4.0, 1],
                ['Skidanje sa linije i odlaganje u korpu', 3.0, 1],
                ['Sečenje izolacije (priprema izolacije)', 20.0, 1],
                ['Lepljenje izolacije na oplatu', 15.0, 1],
                ['Priprema oplate za montažu', 56.0, 2],
                ['Završna montaža oplate', 120.0, 2],
                ['Montaža elektropodsklopova na proizvod', 40.0, 1],
                ['Test bezbednosti i funkcionalnosti', 20.0, 1],
                ['Pakovanje i priprema kotla za transport', 56.0, 1],
            ],
            'TKAN60.xlsx' => [
                ['Pakovanje ,zavarivanje i obrada gornjih vrata (CO2)', 45, 1],
                ['Pakovanje ,zavarivanje i obrada donjih vrata (CO2)', 45, 1],
                ['Pakovanje zavarivanje i obrada zad.poklopaca (CO2)', 40, 1],
                ['Pakovanje i obrada dimnjače (CO2)', 90, 1],
                ['Zavarivanje dimnjače (CO2)', 25, 1],
                ['Pakovanje poda', 100, 2],
                ['Zavarivanje poda (CO2)', 60, 1],
                ['Obrada poda', 45, 1],
                ['Betoniranje poda', 240, 1],
                ['Betoniranje vrata', 120, 1],
                ['Pakovanje I plašta', 300, 2],
                ['Zavarivanje I faze I plašta', 30, 1],
                ['Zavarivanje cevi na I plaštu', 30, 1],
                ['Zavarivanje I plašta (CO2)', 300, 1],
                ['Pakovanje II plašta', 380, 2],
                ['Zavarivanje II plašta (CO2)', 300, 1],
                ['Savijanje krova I plašta (Valjcima)', 30, 1],
                ['Savijanje krova II plašta (Valjcima)', 35, 1],
                ['Kićenje kotla', 380, 2],
                ['Farbanje poda', 20, 1],
                ['Farbanje kotla', 5, 1],
                ['Postavljanje kotla na pod', 30, 1],
                ['Pakovanje I varenje oplate (CO2)', 25, 1],
                ['Punktovanje pozicije oplate', 4, 1],
                ['Brušenje oplate', 20, 1],
                ['Kačenje', 5, 1],
                ['Plasticifiranje', 5, 1],
                ['Skidanje sa linije i odlaganje u korpe', 5, 1],
                ['Secenje izolacije-priprema izolacije', 10, 1],
                ['Lepljenje izolacije na oplatu', 20, 1],
                ['Priprema oplate za montazu', 20, 1],
                ['Zavrsna montaza oplate', 120, 2],
                ['Montaza elektropodsklopova na proizvod', 120, 1],
                ['Programiranje automatike', 10, 1],
                ['Test bezbednosti I funkcionalnosti', 10, 1],
                ['Pakovanje kotla I priprema za transport', 25, 2],
                ['Pakovanje Silosa (priprema za transport)', 10, 2],
                ['Piprema delova za dozere', 120, 1],
                ['Pakovanje i zavarivanje dozera (CO2)', 40, 1],
                ['Farbanje delova dozera', 30, 1],
                ['Kompletiranje dozera', 120, 1],
            ],
            'TKAN80.xlsx' => [
                ['Pakovanje ,zavarivanje i obrada gornjih vrata (CO2)', 90, 1],
                ['Pakovanje ,zavarivanje i obrada donjih vrata (CO2)', 90, 1],
                ['Pakovanje zavarivanje i obrada zad.poklopaca (CO2)', 50, 1],
                ['Pakovanje i obrada dimnjače (CO2)', 200, 1],
                ['Zavarivanje dimnjače (CO2)', 52.5, 1],
                ['Pakovanje poda', 50, 2],
                ['Zavarivanje poda (CO2)', 65, 1],
                ['Obrada poda', 50, 2],
                ['Betoniranje poda', 270, 1],
                ['Betoniranje vrata', 120, 1],
                ['Pakovanje izmenlj.lozista', 30, 2],
                ['Zavarivanje izmen.ložišta (CO2)', 30, 1],
                ['Pakovanje fena', 15, 1],
                ['Pakovanje i zavarivanje spirale za čišćenje (CO2)', 30, 1],
                ['Pakovanje i zavrivanje lule (CO2)', 10, 1],
                ['Pakovanje I plašta', 320, 2],
                ['Zavarivanje I faze I plašta', 30, 1],
                ['Zavarivanje cevi na I plaštu', 30, 1],
                ['Zavarivanje I plašta (CO2)', 300, 1],
                ['Pakovanje II plašta', 380, 2],
                ['Zavarivanje II plašta (CO2)', 300, 1],
                ['Savijanje krova I plašta (Valjcima)', 30, 1],
                ['Savijanje krova II plašta (Valjcima)', 35, 1],
                ['Kićenje kotla', 380, 2],
                ['Farbanje poda', 25, 1],
                ['Farbanje vrata', 5, 1],
                ['Postavljanje kotla na pod', 30, 1],
                ['Pakovanje I varenje oplate (CO2)', 30, 1],
                ['Punktovanje pozicije oplate', 4, 1],
                ['Brušenje oplate', 25, 1],
                ['Kačenje', 5, 1],
                ['Plasticifiranje', 5, 1],
                ['Skidanje sa linije i odlaganje u korpe', 5, 1],
                ['Pakovanje kante za pepeo', 15, 1],
                ['Brušenje kante za pepeo', 10, 1],
                ['Secenje izolacije-priprema izolacije', 20, 1],
                ['Lepljenje izolacije na kotao', 30, 1],
                ['Priprema oplate za montazu', 20, 1],
                ['Zavrsna montaza oplate', 180, 2],
                ['Montaza elektropodsklopova na proizvod', 240, 1],
                ['Programiranje automatike', 10, 1],
                ['Test bezbednosti I funkcionalnosti', 10, 1],
                ['Pakovanje kotla I priprema za transport', 25, 2],
                ['Pakovanje silosa (priprema za transport)', 10, 1],
                ['Piprema delova za dozere', 150, 1],
                ['Pakovanje i zavarivanje dozera (CO2)', 42, 1],
                ['Farbanje delova dozera', 30, 1],
                ['Kompletiranje dozera', 150, 1],
            ],
            'TKAN80integra.xlsx' => [
                ['Pakovanje ,zavarivanje i obrada gornjih vrata (CO2)', 90, 1],
                ['Pakovanje ,zavarivanje i obrada donjih vrata (CO2)', 90, 1],
                ['Pakovanje zavarivanje i obrada zad.poklopaca (CO2)', 50, 1],
                ['Pakovanje i obrada dimnjače (CO2)', 200, 1],
                ['Zavarivanje dimnjače (CO2)', 150, 1],
                ['Pakovanje poda', 100, 1],
                ['Zavarivanje poda (CO2)', 65, 1],
                ['Obrada poda', 50, 1],
                ['Betoniranje poda', 270, 1],
                ['Betoniranje vrata', 120, 1],
                ['Pakovanje izmenlj.lozista', 30, 1],
                ['Zavarivanje izmen.ložišta (CO2)', 30, 1],
                ['Pakovanje fena', 15, 1],
                ['Pakovanje i zavarivanje spirale za čišćenje (CO2)', 30, 1],
                ['Pakovanje i zavrivanje lule (CO2)', 10, 1],
                ['Pakovanje I plašta', 320, 2],
                ['Zavarivanje I faze I plašta', 30, 1],
                ['Zavarivanje cevi na I plaštu', 30, 1],
                ['Zavarivanje I plašta (CO2)', 300, 1],
                ['Pakovanje II plašta', 380, 2],
                ['Zavarivanje II plašta (CO2)', 300, 1],
                ['Savijanje krova I plašta (Valjcima)', 30, 1],
                ['Savijanje krova II plašta (Valjcima)', 35, 1],
                ['Kićenje kotla', 380, 2],
                ['Farbanje poda', 25, 1],
                ['Farbanje vrata', 5, 1],
                ['Postavljanje kotla na pod', 30, 1],
                ['Pakovanje kučišta ciklona', 120, 1],
                ['Zavarivanje kučišta ciklona', 120, 1],
                ['Pakovanje konusa ciklona', 60, 1],
                ['Zavarivanje konusa ciklona', 30, 1],
                ['Pakovanje reducira kućišta ventilatora', 10, 1],
                ['Pakovanje nastavka multiciklona dužeg', 3, 1],
                ['Pakovanje nastavka multiciklona kraćeg', 3, 1],
                ['Zavarivanje nastavka dužeg', 3, 1],
                ['Zavarivanje nastavka kraćeg', 3, 1],
                ['Zavarivanje reducira kućišta ventilatora', 10, 1],
                ['Pakovanje ciklon kante za pepeo', 40, 1],
                ['Zavarivanje ciklon kante za pepeo', 45, 1],
                ['Pakovanje dimnjače ciklona', 60, 1],
                ['Zavarivanje dimnjače ciklona', 30, 1],
                ['Obrada ciklon kante za pepeo', 30, 1],
                ['Obrada kučišta ciklona', 30, 1],
                ['Montaža turbine ventilatora i kućišta', 120, 1],
                ['Finalna montaža sklopa ciklona (bez ventilatora)', 350, 1],
                ['Pakovanje I varenje oplate (CO2)', 30, 1],
                ['Punktovanje pozicije oplate', 4, 1],
                ['Brušenje oplate', 25, 1],
                ['Kačenje', 5, 1],
                ['Plasticifiranje', 5, 1],
                ['Skidanje sa linije i odlaganje u korpe', 5, 1],
                ['Secenje izolacije-priprema izolacije', 20, 1],
                ['Lepljenje izolacije', 30, 1],
                ['Priprema oplate za montazu', 20, 1],
                ['Zavrsna montaza oplate', 180, 2],
                ['Montaza elektropodsklopova na proizvod', 240, 1],
                ['Programiranje automatike', 10, 1],
                ['Test bezbednosti I funkcionalnosti', 10, 1],
                ['Pakovanje kotla I priprema za transport', 25, 2],
                ['Pakovanje silosa (priprema za transport)', 10, 1],
                ['Piprema delova za dozere', 150, 1],
                ['Pakovanje i zavarivanje dozera (CO2)', 42, 1],
                ['Farbanje delova dozera', 30, 1],
                ['Kompletiranje dozera', 150, 1],
            ],
            'TKAN100.xlsx' => [
                ['Pakovanje ,zavarivanje i obrada gornjih vrata (CO2)', 90, 1],
                ['Pakovanje ,zavarivanje i obrada donjih vrata (CO2)', 90, 1],
                ['Pakovanje zavarivanje i obrada zad.poklopaca (CO2)', 50, 1],
                ['Pakovanje i obrada dimnjače', 200, 1],
                ['Zavarivanje dimnjače', 52.5, 1],
                ['Pakovanje poda', 120, 2],
                ['Zavarivanje poda (CO2)', 90, 1],
                ['Obrada poda', 84, 1],
                ['Betoniranje poda', 270, 1],
                ['Betoniranje vrata', 120, 1],
                ['Pakovanje izmenlj.lozista', 30, 1],
                ['Zavarivanje izmen.ložišta (CO2)', 30, 1],
                ['Pakovanje fena', 15, 1],
                ['Pakovanje i zavarivanje spirale za čišćenje (CO2)', 45, 1],
                ['Pakovanje i zavrivanje lule (CO2)', 10, 1],
                ['Pakovanje I plašta', 340, 2],
                ['Zavarivanje I faze I plašta', 30, 1],
                ['Zavarivanje cevi na I plaštu', 30, 1],
                ['Zavarivanje I plašta (CO2)', 300, 1],
                ['Pakovanje II plašta', 380, 2],
                ['Zavarivanje II plašta (CO2)', 320, 1],
                ['Savijanje krova I plašta (Valjcima)', 35, 1],
                ['Savijanje krova II plašta (Valjcima)', 40, 1],
                ['Kićenje kotla', 420, 2],
                ['Farbanje poda', 35, 1],
                ['Farbanje kotla', 5, 1],
                ['Postavljanje kotla na pod', 30, 1],
                ['Pakovanje I varenje oplate (CO2)', 30, 1],
                ['Punktovanje pozicije oplate', 4, 1],
                ['Brušenje oplate', 25, 1],
                ['Kačenje', 5, 1],
                ['Plastificiranje', 5, 1],
                ['Skidanje sa linije i odlaganje u korpe', 5, 1],
                ['Brušenje kante za pepeo', 10, 1],
                ['Pakovanje kante za pepeo', 15, 1],
                ['Secenje izolacije-priprema izolacije', 20, 1],
                ['Lepljenje izolacije', 30, 1],
                ['Priprema oplate za montazu', 20, 1],
                ['Zavrsna montaza oplate', 180, 2],
                ['Montaza elektropodsklopova na proizvod', 240, 1],
                ['Programiranje automatike', 10, 1],
                ['Test bezbednosti I funkcionalnosti', 10, 1],
                ['Pakovanje kotla I priprema za transport', 30, 2],
                ['Pakovanje silosa (priprema za transport)', 10, 2],
                ['Piprema delova za dozere', 240, 1],
                ['Pakovanje i zavarivanje dozera (CO2)', 70, 1],
                ['Farbanje delova dozera', 35, 1],
                ['Kompletiranje dozera', 240, 1],
            ],
            'TKAN100Integra' => [
                ['Pakovanje ,zavarivanje i obrada gornjih vrata (CO2)', 90, 1],
                ['Pakovanje ,zavarivanje i obrada donjih vrata (CO2)', 90, 1],
                ['Pakovanje zavarivanje i obrada zad.poklopaca (CO2)', 50, 1],
                ['Pakovanje i obrada dimnjače', 200, 1],
                ['Zavarivanje dimnjače', 150, 1],
                ['Pakovanje poda', 120, 2],
                ['Zavarivanje poda (CO2)', 90, 1],
                ['Obrada poda', 84, 1],
                ['Betoniranje poda', 270, 1],
                ['Betoniranje vrata', 120, 1],
                ['Pakovanje izmenlj.lozista', 30, 1],
                ['Zavarivanje izmen.ložišta (CO2)', 30, 1],
                ['Pakovanje fena', 15, 1],
                ['Pakovanje i zavarivanje spirale za čišćenje (CO2)', 45, 1],
                ['Pakovanje i zavrivanje lule (CO2)', 10, 1],
                ['Pakovanje I plašta', 400, 2],
                ['Zavarivanje I faze I plašta', 30, 1],
                ['Zavarivanje cevi na I plaštu', 30, 1],
                ['Zavarivanje I plašta (CO2)', 300, 1],
                ['Pakovanje II plašta', 380, 2],
                ['Zavarivanje II plašta (CO2)', 300, 1],
                ['Savijanje krova I plašta (Valjcima)', 35, 1],
                ['Savijanje krova II plašta (Valjcima)', 40, 1],
                ['Kićenje kotla', 420, 2],
                ['Farbanje poda', 35, 1],
                ['Farbanje kotla', 5, 1],
                ['Postavljanje kotla na pod', 30, 1],
                ['Pakovanje kućišta ciklona', 150, 1],
                ['Zavarivanje kućišta ciklona', 150, 1],
                ['Pakovanje konusa ciklona', 60, 1],
                ['Zavarivanje konusa ciklona', 40, 1],
                ['Pakovanje reducira kučišta ventilatora', 10, 1],
                ['Pakovanje nastavka multiciklona dužeg', 3, 1],
                ['Pakovanje nastavka multiciklona kraćeg', 3, 1],
                ['Zavarivanje nastavka dužeg', 3, 1],
                ['Zavarivanje nastavka kraćeg', 3, 1],
                ['Zavarivanje reducira kučišta ventilatora', 10, 1],
                ['Pakovanje kučišta ventilatora', 150, 1],
                ['Zavarivanje kučišta ventilatora', 90, 1],
                ['Montaža turbine ventilatora i kučišta', 120, 1],
                ['Pakovanje ciklon kante za pepeo', 60, 1],
                ['Zavarivanje ciklon kante za pepeo', 45, 1],
                ['Finalna montaža sklopa ciklona (bez ventilatora)', 280, 1],
                ['Pakovanje dimnjače ciklona', 60, 1],
                ['Zavarivanje dimnjače ciklona', 35, 1],
                ['Obrada ciklon kante za pepeo', 25, 1],
                ['Obrada kučišta ciklona', 25, 1],
                ['Pakovanje I varenje oplate (CO2)', 35, 1],
                ['Punktovanje pozicije oplate', 4, 1],
                ['Brušenje oplate', 25, 1],
                ['Kačenje', 5, 1],
                ['Plastificiranje', 5, 1],
                ['Skidanje sa linije i odlaganje u korpe', 5, 1],
                ['Brušenje kante za pepeo', 10, 1],
                ['Pakovanje kante za pepeo', 15, 1],
                ['Secenje izolacije-priprema izolacije', 40, 1],
                ['Lepljenje izolacije', 60, 1],
                ['Priprema oplate za montazu', 40, 1],
                ['Zavrsna montaza oplate', 300, 2],
                ['Montaza elektropodsklopova na proizvod', 300, 1],
                ['Programiranje automatike', 10, 1],
                ['Test bezbednosti I funkcionalnosti', 10, 1],
                ['Pakovanje kotla I priprema za transport', 35, 2],
                ['Pakovanje silosa (priprema za transport)', 10, 1],
                ['Piprema delova za dozere', 240, 1],
                ['Pakovanje i zavarivanje dozera (CO2)', 70, 1],
                ['Farbanje delova dozera', 45, 1],
                ['Kompletiranje dozera', 240, 1],
            ],
            'TKAN150' => [
                ['Pakovanje ,zavarivanje i obrada gornjih vrata (CO2)', 100, 1],
                ['Pakovanje ,zavarivanje i obrada donjih vrata (CO2)', 100, 1],
                ['Pakovanje zavarivanje i obrada zad.poklopaca (CO2)', 70, 1],
                ['Pakovanje i obrada dimnjače (CO2)', 220, 1],
                ['Zavarivanje dimnjače (CO2)', 60, 1],
                ['Pakovanje poda', 150, 2],
                ['Zavarivanje poda (CO2)', 100, 1],
                ['Obrada poda', 90, 1],
                ['Betoniranje poda', 270, 1],
                ['Betoniranje vrata', 120, 1],
                ['Pakovanje izmenlj.lozista', 30, 1],
                ['Zavarivanje izmen.ložišta (CO2)', 30, 1],
                ['Pakovanje fena', 15, 1],
                ['Pakovanje i zavarivanje spirale za čišćenje (CO2)', 45, 1],
                ['Pakovanje i zavrivanje lule (CO2)', 10, 1],
                ['Pakovanje I plašta', 550, 2],
                ['Zavarivanje I faze I plašta', 30, 1],
                ['Zavarivanje cevi na I plaštu', 30, 1],
                ['Zavarivanje I plašta (CO2)', 300, 1],
                ['Pakovanje II plašta', 400, 2],
                ['Zavarivanje II plašta (CO2)', 380, 1],
                ['Savijanje krova I plašta (Valjcima)', 35, 1],
                ['Savijanje krova II plašta (Valjcima)', 40, 1],
                ['Kićenje kotla', 420, 2],
                ['Farbanje poda', 35, 1],
                ['Farbanje kotla', 5, 1],
                ['Postavljanje kotla na pod', 30, 1],
                ['Pakovanje I varenje oplate (CO2)', 35, 1],
                ['Punktovanje pozicije oplate', 4, 1],
                ['Brušenje oplate', 25, 1],
                ['Kačenje', 5, 1],
                ['Plastificiranje', 5, 1],
                ['Skidanje sa linije i odlaganje u korpe', 5, 1],
                ['Pakovanje kante za pepeo', 15, 1],
                ['Brušenje kante za pepeo', 10, 1],
                ['Secenje izolacije-priprema izolacije', 30, 1],
                ['Lepljenje izolacije', 50, 1],
                ['Priprema oplate za montazu', 40, 1],
                ['Zavrsna montaza oplate', 360, 2],
                ['Montaza elektropodsklopova na proizvod', 360, 1],
                ['Programiranje automatike', 10, 1],
                ['Test bezbednosti I funkcionalnosti', 10, 1],
                ['Pakovanje kotla I priprema za transport', 40, 2],
                ['Pakovanje silosa (priprema za transport)', 15, 1],
                ['Priprema delova za dozere', 300, 1],
                ['Pakovanje i zavarivanje dozera (CO2)', 70, 1],
                ['Farbanje delova dozera', 45, 1],
                ['Kompletiranje dozera', 300, 1],
            ],
            'TKAN150Integra' => [
                ['Pakovanje, zavarivanje I obrada gornjih vrata (CO2)', 100.0, 1],
                ['Pakovanje, zavarivanje I obrada donjih vrata (CO2)', 100.0, 1],
                ['Pakovanje, zavarivanje I obrada zad.poklopca (CO2)', 70.0, 1],
                ['Pakovanje ložišta', 150.0, 2],
                ['Zavarivanje ložišta(CO2)', 100.0, 1],
                ['Obrada ložišta', 90.0, 1],
                ['Betoniranje ložišta', 270.0, 1],
                ['Betoniranje vrata', 120.0, 1],
                ['Pakovanje koncentrične redukcije', 12.5, 1],
                ['Zavarivanje koncentrične redukcije', 13.0, 1],
                ['Obrada koncentrične redukcije', 5.0, 1],
                ['Pakovanje kutije otprašivača', 30.0, 1],
                ['Zavarivanje kutije otprašivača', 15.0, 1],
                ['Obrada kutije otprašivača', 5.0, 1],
                ['Pakovanje omotača boce za otprašivanje 10l', 30.0, 1],
                ['Zavarivanje omotača boce za otprašivanje iznutra 10l', 5.0, 1],
                ['Pakovanje danca i omotača 10l', 20.0, 1],
                ['Pakovanje mufova,nosača tablice I nogara boce za otprašivanje 10L', 40.0, 1],
                ['Zavarivanje mufova,nosača tablice I nogara boce za otprašivanje 10L', 20.0, 1],
                ['Obrada - Čišćenje boce za otprašivanje 10L', 20.0, 1],
                ['Hidro test boce za otprašivanje 10L', 30.0, 1],
                ['Farbanje ložišta', 30.0, 1],
                ['Farbanje izmenjivača', 90.0, 1],
                ['Farbanje ciklona', 30.0, 1],
                ['Farbanje kante', 15.0, 1],
                ['Farbanje kosine', 20.0, 1],
                ['Pakovanje i zavarivanje spirale za čišćenje', 45.0, 1],
                ['Pakovanje i zavarivanje Lule', 10.0, 1],
                ['Pakovanje fena', 15.0, 1],
                ['Pakovanje I plašta', 550.0, 2],
                ['Zavarivanje I faze I plašta', 30.0, 1],
                ['Zavarivanje cevi na I plaštu', 30.0, 1],
                ['Zavarivanje I plašta (CO2)', 300.0, 1],
                ['Pakovanje II plašta', 400.0, 2],
                ['Zavarivanje II plašta (CO2)', 380.0, 1],
                ['Savijanje krova I plašta (valjcima)', 35.0, 1],
                ['Savijanje krova II plašta (valjcima)', 40.0, 1],
                ['Postavljanje izmenjivača na ložište', 30.0, 1],
                ['Pakovanje kučišta ciklona', 160.0, 1],
                ['Zavarivanje kučišta ciklona', 160.0, 1],
                ['Pakovanje konusa ciklona', 60.0, 1],
                ['Zavarivanje konusa ciklona', 40.0, 1],
                ['Pakovanje reducira kućišta ventilatora', 10.0, 1],
                ['Pakovanje nastavka multiciklona dužeg', 3.0, 1],
                ['Pakovanje nastavka multiciklona kraćeg', 3.0, 1],
                ['Zavarivanje nastavka dužeg', 3.0, 1],
                ['Zavarivanje nastavka kraćeg', 3.0, 1],
                ['Zavarivanje reducira kućišta ventilatora', 10.0, 1],
                ['Pakovanje kućišta ventilatora', 150.0, 1],
                ['Zavarivanje kućišta ventilatora', 90.0, 1],
                ['Montaža turbine ventilatora i kućišta', 120.0, 1],
                ['Pakovanje ciklon kante za pepeo', 60.0, 1],
                ['Zavarivanje ciklon kante za pepeo', 45.0, 1],
                ['Finalna montaža sklopa ciklona', 280.0, 1],
                ['Pakovanje dimnjače ciklona', 60.0, 1],
                ['Zavarivanje dimnjače ciklona', 40.0, 1],
                ['Obrada ciklon kante za pepeo', 30.0, 1],
                ['Obrada kućišta ciklona', 30.0, 1],
                ['Pakovanje i zavarivanje dozera (CO2)', 75.0, 1],
                ['Farbanje delova dozera', 45.0, 1],
                ['Kompletiranje dozera', 300.0, 1],
                ['Pakovanje i varenje oplate (CO2)', 35.0, 1],
                ['Punktovanje pozicija oplate', 4.0, 1],
                ['Brušenje oplate', 25.0, 1],
                ['Kačenje', 5.0, 1],
                ['Plastificiranje', 5.0, 1],
                ['Skidanje sa linije i odlaganje u korpe', 5.0, 1],
                ['Pakovanje kante za pepeo', 15.0, 1],
                ['Brušenje kante za pepeo', 10.0, 1],
                ['Sečenje izolacije', 30.0, 1],
                ['Postavljanje izolacije', 50.0, 1],
                ['Priprema oplate za montažu', 40.0, 1],
                ['Montaža elektro ormara i ožičenja na oplatu', 360.0, 1],
                ['Završna montaža oplate i sklopova', 360.0, 1],
                ['Test bezbednosti i funkcionalnosti', 10.0, 1],
                ['Pakovanje i priprema za transport', 40.0, 1],
                ['Pakovanje silosa', 15.0, 1],
            ],
            'TKAN200' => [
                ['Pakovanje, zavarivanje i obrada gornjih vrata (CO2)', 100.0, 1],
                ['Pakovanje, zavarivanje i obrada donjih vrata (CO2)', 100.0, 1],
                ['Pakovanje, zavarivanje i obrada zad.poklopaca (CO2)', 80.0, 1],
                ['Pakovanje, zavarivanje i obrada prednjeg poklopca', 60.0, 1],
                ['Pakovanje i obrada dimnjače (CO2)', 220.0, 1],
                ['Zavarivanje dimnjače (CO2)', 60.0, 1],
                ['Pakovanje poda', 180.0, 2],
                ['Zavarivanje poda (CO2)', 105.0, 1],
                ['Obrada poda', 145.0, 1],
                ['Betoniranje poda', 270.0, 1],
                ['Betoniranje vrata', 120.0, 1],
                ['Pakovanje izmenljivog ložišta', 30.0, 1],
                ['Zavarivanje izmenljivog ložišta (CO2)', 30.0, 1],
                ['Pakovanje fena', 15.0, 1],
                ['Pakovanje i zavarivanje spirale za čišćenje (CO2)', 50.0, 1],
                ['Pakovanje i zavarivanje lule (CO2)', 10.0, 1],
                ['Pakovanje I plašta', 550.0, 2],
                ['Zavarivanje I faze I plašta', 35.0, 1],
                ['Zavarivanje cevi na I plaštu', 35.0, 1],
                ['Zavarivanje I plašta (CO2)', 330.0, 1],
                ['Pakovanje II plašta', 400.0, 2],
                ['Zavarivanje II plašta (CO2)', 400.0, 1],
                ['Savijanje krova I plašta (Valjcima)', 40.0, 1],
                ['Savijanje krova II plašta (Valjcima)', 45.0, 1],
                ['Kićenje kotla', 420.0, 2],
                ['Farbanje poda', 30.0, 1],
                ['Farbanje vrata', 5.0, 1],
                ['Postavljanje kotla na pod', 30.0, 1],
                ['Pakovanje I varenje oplate (CO2)', 35.0, 1],
                ['Punktovanje pozicije oplate', 4.0, 1],
                ['Brušenje oplate', 25.0, 1],
                ['Kačenje', 5.0, 1],
                ['Plastificiranje', 5.0, 1],
                ['Skidanje sa linije i odlaganje u korpe', 5.0, 1],
                ['Pakovanje kante za pepeo', 15.0, 1],
                ['Brušenje kante za pepeo', 10.0, 1],
                ['Sečenje izolacije - priprema izolacije', 30.0, 1],
                ['Lepljenje izolacije', 50.0, 1],
                ['Priprema oplate za montažu', 40.0, 1],
                ['Završna montaža oplate', 360.0, 2],
                ['Montaža elektropodsklopova na proizvod', 360.0, 1],
                ['Programiranje automatike', 10.0, 1],
                ['Test bezbednosti i funkcionalnosti', 10.0, 1],
                ['Pakovanje kotla i priprema za transport', 40.0, 2],
                ['Pakovanje silosa (priprema za transport)', 15.0, 1],
                ['Priprema delova za dozere', 300.0, 1],
                ['Pakovanje i zavarivanje dozera (CO2)', 70.0, 1],
                ['Farbanje delova dozera', 45.0, 1],
                ['Kompletiranje dozera', 300.0, 1],
            ],
            'TKAN200integra' => [
                ['Pakovanje ,zavarivanje i obrada gornjih vrata (CO2)', 145.0, 1],
                ['Pakovanje ,zavarivanje i obrada donjih vrata (CO2)', 145.0, 1],
                ['Pakovanje zavarivanje i obrada zad.poklopaca (CO2)', 80.0, 1],
                ['Pakovanje,zavarivanje i obrada prednjeg poklopca', 60.0, 1],
                ['Pakovanje poda', 180.0, 2],
                ['Zavarivanje poda (CO2)', 105.0, 1],
                ['Obrada poda', 150.0, 1],
                ['Betoniranje poda', 270.0, 1],
                ['Betoniranje vrata', 120.0, 1],
                ['Pakovanje izmenlj.lozista', 30.0, 1],
                ['Zavarivanje izmen.ložišta (CO2)', 30.0, 1],
                ['Pakovanje fena', 15.0, 1],
                ['Pakovanje i zavarivanje spirale za čišćenje (CO2)', 50.0, 1],
                ['Pakovanje i zavrivanje lule (CO2)', 10.0, 1],
                ['Pakovanje kutije otprašivača', 30.0, 1],
                ['Zavarivanje kutije otprašivača', 15.0, 1],
                ['Obrada kutije otprašivača', 5.0, 1],
                ['Pakovanje omotača boce za otprašivanje 24L', 30.0, 1],
                ['Zavarivanje omotača boce za otprašivanje iznutra 24L', 8.0, 1],
                ['Pakovanje danca i omotača (24l)', 24.0, 1],
                ['Pakovanje mufova,nosača tablice I nogara boce za otprašivanje 24L', 46.0, 1],
                ['Zavarivanje mufova,nosača tablice I nogara boce za otprašivanje 24L', 25.0, 1],
                ['Obrada - Čišćenje boce za otprašivanje 24L', 25.0, 1],
                ['Hidro test boce za otprašivanje 24L', 30.0, 1],
                ['Pakovanje I plašta', 580.0, 2],
                ['Zavarivanje I faze I plašta', 35.0, 1],
                ['Zavarivanje cevi na I plaštu', 35.0, 1],
                ['Zavarivanje I plašta (CO2)', 350.0, 1],
                ['Pakovanje II plašta', 420.0, 2],
                ['Zavarivanje II plašta (CO2)', 400.0, 1],
                ['Savijanje krova I plašta (Valjcima)', 40.0, 1],
                ['Savijanje krova II plašta (Valjcima)', 45.0, 1],
                ['Kićenje kotla', 420.0, 2],
                ['Farbanje poda', 30.0, 1],
                ['Farbanje izmenjivača', 90.0, 1],
                ['Farbanje ložišta', 30.0, 1],
                ['Farbanje kosine', 20.0, 1],
                ['Farbanje kante', 30.0, 1],
                ['Farbanje vrata', 15.0, 1],
                ['Postavljanje kotla na pod', 30.0, 1],
                ['Pakovanje kučišta ciklona', 180.0, 1],
                ['Zavarivanje kučišta ciklona', 180.0, 1],
                ['Pakovanje konusa ciklona', 60.0, 1],
                ['Zavarivanje konusa ciklona', 50.0, 1],
                ['Pakovanje reducira kućišta ventilatora', 10.0, 1],
                ['Pakovanje nastavka multiciklona dužeg', 3.0, 1],
                ['Pakovanje nastavka multiciklona kraćeg', 3.0, 1],
                ['Zavarivanje nastavka dužeg', 3.0, 1],
                ['Zavarivanje nastavka kraćeg', 3.0, 1],
                ['Zavarivanje reducira kućišta ventilatora', 10.0, 1],
                ['Pakovanje kućišta ventilatora', 170.0, 1],
                ['Zavarivanje kućišta ventilatora', 110.0, 1],
                ['Montaža turbine vantilatora i kućišta', 120.0, 1],
                ['Pakovanje ciklon kante za pepeo', 50.0, 1],
                ['Zavarivanje ciklon kante za pepeo', 45.0, 1],
                ['Finalna montaža sklopa ciklona (bez ventilatora)', 280.0, 1],
                ['Pakovanje dimnjače ciklona', 50.0, 1],
                ['Zavarivanje dimnjače ciklona', 50.0, 1],
                ['Obrada ciklon kante za pepeo', 30.0, 1],
                ['Obrada kučišta ciklona', 35.0, 1],
                ['Pakovanje I varenje oplate (CO2)', 35.0, 1],
                ['Punktovanje pozicije oplate', 4.0, 1],
                ['Brušenje oplate', 25.0, 1],
                ['Kačenje', 5.0, 1],
                ['Plastificiranje', 5.0, 1],
                ['Skidanje sa linije i odlaganje u korpe', 5.0, 1],
                ['Pakovanje kante za pepeo', 15.0, 1],
                ['Brušenje kante za pepeo', 10.0, 1],
                ['Secenje izolacije-priprema izolacije', 40.0, 1],
                ['Lepljenje izolacije', 60.0, 1],
                ['Priprema oplate za montazu', 60.0, 2],
                ['Zavrsna montaza oplate', 360.0, 2],
                ['Montaza elektropodsklopova na proizvod', 360.0, 1],
                ['Programiranje automatike', 10.0, 1],
                ['Test bezbednosti I funkcionalnosti', 10.0, 1],
                ['Pakovanje kotla I priprema za transport', 45.0, 2],
                ['Pakovanje silosa (priprema za transport)', 10.0, 2],
                ['Piprema delova za dozere', 300.0, 1],
                ['Pakovanje i zavarivanje dozera (CO2)', 70.0, 1],
                ['Farbanje delova dozera', 45.0, 1],
                ['Kompletiranje dozera', 300.0, 1],
            ],
            'TKAN250' => [
                ['Pakovanje ,zavarivanje i obrada gornjih vrata (CO2)', 220.0, 1],
                ['Pakovanje ,zavarivanje i obrada donjih vrata (CO2)', 200.0, 1],
                ['Pakovanje zavarivanje i obrada zad.poklopaca (CO2)', 100.0, 1],
                ['Pakovanje,zavarivanje i obrada prednjeg poklopca', 60.0, 1],
                ['Pakovanje i obrada dimnjače (CO2)', 220.0, 1],
                ['Zavarivanje dimnjače (CO2)', 80.0, 1],
                ['Pakovanje poda', 210.0, 2],
                ['Zavarivanje poda (CO2)', 250.0, 1],
                ['Obrada poda', 150.0, 1],
                ['Betoniranje poda', 300.0, 1],
                ['Betoniranje vrata', 150.0, 1],
                ['Pakovanje izmenlj.lozista', 50.0, 1],
                ['Zavarivanje izmen.ložišta (CO2)', 60.0, 1],
                ['Pakovanje fena', 15.0, 1],
                ['Pakovanje i zavarivanje spirale za čišćenje (CO2)', 60.0, 1],
                ['Pakovanje i zavrivanje lule (CO2)', 10.0, 1],
                ['Pakovanje I plašta', 600.0, 2],
                ['Zavarivanje I faze I plašta', 45.0, 1],
                ['Zavarivanje cevi na I plaštu', 45.0, 1],
                ['Zavarivanje I plašta (CO2)', 420.0, 1],
                ['Pakovanje II plašta', 560.0, 2],
                ['Zavarivanje II plašta (CO2)', 600.0, 1],
                ['Savijanje krova I plašta (Valjcima)', 45.0, 1],
                ['Savijanje krova II plašta (Valjcima)', 50.0, 1],
                ['Kićenje kotla', 420.0, 2],
                ['Farbanje poda', 30.0, 1],
                ['Farbanje vrata', 5.0, 1],
                ['Postavljanje kotla na pod', 30.0, 1],
                ['Pakovanje I varenje oplate (CO2)', 40.0, 1],
                ['Punktovanje pozicije oplate', 4.0, 1],
                ['Brušenje oplate', 30.0, 1],
                ['Kačenje', 5.0, 1],
                ['Plastificiranje', 5.0, 1],
                ['Skidanje sa linije i odlaganje u korpe', 5.0, 1],
                ['Pakovanje kante za pepeo', 15.0, 1],
                ['Brušenje kante za pepeo', 10.0, 1],
                ['Secenje izolacije-priprema izolacije', 30.0, 1],
                ['Lepljenje izolacije', 60.0, 1],
                ['Priprema oplate za montazu', 60.0, 2],
                ['Zavrsna montaza oplate', 360.0, 2],
                ['Montaza elektropodsklopova na proizvod', 360.0, 1],
                ['Programiranje automatike', 10.0, 1],
                ['Test bezbednosti I funkcionalnosti', 10.0, 1],
                ['Pakovanje kotla I priprema za transport', 45.0, 2],
                ['Pakovanje silosa (priprema za transport)', 20.0, 2],
                ['Piprema delova za dozere', 300.0, 1],
                ['Pakovanje i zavarivanje dozera (CO2)', 70.0, 1],
                ['Farbanje delova dozera', 45.0, 1],
                ['Kompletiranje dozera', 300.0, 1],
            ],
            'TKAN250integra' => [
                ['Pakovanje, zavarivanje I obrada gornjih vrata (CO2)', 220.0, 1],
                ['Pakovanje, zavarivanje I obrada donjih vrata (CO2)', 200.0, 1],
                ['Pakovanje, zavarivanje I obrada zad.poklopca (CO2)', 100.0, 1],
                ['Pakovanje, zavarivanje I obrada prednjeg poklopca (CO2)', 60.0, 1],
                ['Pakovanje poda', 210.0, 2],
                ['Zavarivanje poda', 315.0, 1],
                ['Obrada poda', 160.0, 1],
                ['Betoniranje poda', 300.0, 1],
                ['Betoniranje vrata', 150.0, 1],
                ['Farbanje ložišta', 30.0, 1],
                ['Farbanje kosine', 20.0, 1],
                ['Pakovanje koncentrične redukcije', 12.5, 1],
                ['Zavarivanje koncentrične redukcije', 13.0, 1],
                ['Obrada koncentrične redukcije', 5.0, 1],
                ['Pakovanje i zavarivanje spirale za čišćenje', 60.0, 1],
                ['Pakovanje kutije otprašivača', 40.0, 1],
                ['Zavarivanje kutije otprašivača', 20.0, 1],
                ['Obrada kutije otprašivača', 5.0, 1],
                ['Pakovanje omotača boce za otprašivanje 24L', 30.0, 1],
                ['Zavarivanje omotača boce za otprašivanje iznutra 24L', 8.0, 1],
                ['Pakovanje danca i omotača (24l)', 24.0, 1],
                ['Pakovanje mufova,nosača tablice I nogara boce za otprašivanje 24L', 46.0, 1],
                ['Zavarivanje mufova,nosača tablice I nogara boce za otprašivanje 24L', 25.0, 1],
                ['Obrada - Čišćenje boce za otprašivanje 24L', 25.0, 1],
                ['Hidro test boce za otprašivanje 24L', 30.0, 1],
                ['Pakovanje I plašta', 950.0, 2],
                ['Zavarivanje I faze I plašta', 45.0, 1],
                ['Zavarivanje cevi na I plaštu', 45.0, 1],
                ['Zavarivanje I plašta (CO2)', 420.0, 1],
                ['Pakovanje II plašta', 700.0, 2],
                ['Zavarivanje II plašta (CO2)', 600.0, 1],
                ['Savijanje krova I plašta (valjcima)', 45.0, 1],
                ['Savijanje krova II plašta (valjcima)', 50.0, 1],
                ['Postavljanje kotla na pod', 30.0, 1],
                ['Kićenje', 420.0, 2],
                ['Pakovanje i zavarivanje dozera (CO2)', 70.0, 1],
                ['Farbanje delova dozera', 45.0, 1],
                ['Kompletiranje dozera', 300.0, 1],
                ['Pakovanje kućišta ciklona', 200.0, 1],
                ['Zavarivanje kućišta ciklona', 200.0, 1],
                ['Pakovanje konusa ciklona', 60.0, 1],
                ['Zavarivanje konusa ciklona', 60.0, 1],
                ['Pakovanje reducira kućišta ventilatora', 10.0, 1],
                ['Pakovanje nastavka multiciklona dužeg', 3.0, 1],
                ['Pakovanje nastavka multiciklona kraćeg', 3.0, 1],
                ['Zavarivanje nastavka dužeg', 3.0, 1],
                ['Zavarivanje nastavka kraćeg', 3.0, 1],
                ['Zavarivanje reducira kućišta ventilatora', 20.0, 1],
                ['Pakovanje kućišta ventilatora', 180.0, 1],
                ['Zavarivanje kućišta ventilatora', 120.0, 1],
                ['Montaža turbine ventilatora i kućišta', 120.0, 1],
                ['Pakovanje ciklon kante za pepeo', 60.0, 1],
                ['Zavarivanje ciklon kante za pepeo', 45.0, 1],
                ['Finalna montaža sklopa ciklona (bez ventilatora)', 280.0, 1],
                ['Pakovanje dimnjače ciklona', 60.0, 1],
                ['Zavarivanje dimnjače ciklona', 60.0, 1],
                ['Obrada ciklon kante ze pepeo', 30.0, 1],
                ['Obrada kućišta ciklona', 40.0, 1],
                ['Pakovanje i varenje oplate (CO2)', 40.0, 1],
                ['Punktovanje pozicija oplate', 4.0, 1],
                ['Brušenje oplate', 30.0, 1],
                ['Kačenje', 5.0, 1],
                ['Plastificiranje', 5.0, 1],
                ['Skidanje sa linije i odlaganje u korpe', 5.0, 1],
                ['Pakovanje kante za pepeo', 15.0, 1],
                ['Brušenje kante za pepeo', 10.0, 1],
                ['Priprema izolacije', 50.0, 1],
                ['Postavljanje izolacije', 60.0, 1],
                ['Priprema oplate za montažu', 50.0, 2],
                ['Montaža elektro ormara i ožičenja na oplatu', 360.0, 1],
                ['Završna montaža oplate i sklopova', 480.0, 2],
                ['Test bezbednosti i funkcionalnosti', 10.0, 1],
                ['Pakovanje i priprema za transport', 45.0, 2],
                ['Pakovanje silosa (priprema za transport)', 30.0, 2],
            ],
            'TKAN300' => [
                ['Pakovanje ,zavarivanje i obrada gornjih vrata (CO2)', 220, 1],
                ['Pakovanje ,zavarivanje i obrada donjih vrata (CO2)', 200, 1],
                ['Pakovanje zavarivanje i obrada zad.poklopaca (CO2)', 100, 1],
                ['Pakovanje,zavarivanje i obrada prednjeg poklopca', 60, 1],
                ['Pakovanje i obrada dimnjače (CO2)', 220, 1],
                ['Zavarivanje dimnjače (CO2)', 80, 1],
                ['Pakovanje poda', 210, 2],
                ['Zavarivanje poda (CO2)', 250, 1],
                ['Obrada poda', 150, 1],
                ['Betoniranje poda', 300, 1],
                ['Betoniranje vrata', 150, 1],
                ['Pakovanje izmenlj.lozista', 50, 1],
                ['Zavarivanje izmen.ložišta (CO2)', 60, 1],
                ['Pakovanje fena', 15, 1],
                ['Pakovanje i zavarivanje spirale za čišćenje (CO2)', 60, 1],
                ['Pakovanje i zavrivanje lule (CO2)', 10, 1],
                ['Pakovanje I plašta', 600, 2],
                ['Zavarivanje I faze I plašta', 45, 1],
                ['Zavarivanje cevi na I plaštu', 45, 1],
                ['Zavarivanje I plašta (CO2)', 420, 1],
                ['Pakovanje II plašta', 560, 2],
                ['Zavarivanje II plašta (CO2)', 600, 1],
                ['Savijanje krova I plašta (Valjcima)', 45, 1],
                ['Savijanje krova II plašta (Valjcima)', 50, 1],
                ['Kićenje kotla', 420, 2],
                ['Farbanje poda', 30, 1],
                ['Farbanje vrata', 5, 1],
                ['Postavljanje kotla na pod', 30, 1],
                ['Pakovanje I varenje oplate (CO2)', 40, 1],
                ['Punktovanje pozicije oplate', 4, 1],
                ['Brušenje oplate', 30, 1],
                ['Kačenje', 5, 1],
                ['Plastificiranje', 5, 1],
                ['Skidanje sa linije i odlaganje u korpe', 5, 1],
                ['Pakovanje kante za pepeo', 15, 1],
                ['Brušenje kante za pepeo', 10, 1],
                ['Secenje izolacije-priprema izolacije', 30, 1],
                ['Lepljenje izolacije', 60, 1],
                ['Priprema oplate za montazu', 60, 2],
                ['Zavrsna montaza oplate', 360, 2],
                ['Montaza elektropodsklopova na proizvod', 360, 1],
                ['Programiranje automatike', 10, 1],
                ['Test bezbednosti I funkcionalnosti', 10, 1],
                ['Pakovanje kotla I priprema za transport', 45, 2],
                ['Pakovanje silosa (priprema za transport)', 20, 2],
                ['Piprema delova za dozere', 300, 1],
                ['Pakovanje i zavarivanje dozera (CO2)', 70, 1],
                ['Farbanje delova dozera', 45, 1],
                ['Kompletiranje dozera', 300, 1],
            ],
            'TKAN300integra' => [
                ['Pakovanje, zavarivanje I obrada gornjih vrata (CO2)', 220.0, 1],
                ['Pakovanje, zavarivanje I obrada donjih vrata (CO2)', 200.0, 1],
                ['Pakovanje, zavarivanje I obrada zad.poklopca (CO2)', 100.0, 1],
                ['Pakovanje, zavarivanje I obrada prednjeg poklopca (CO2)', 60.0, 1],
                ['Pakovanje poda', 210.0, 2],
                ['Zavarivanje poda', 315.0, 1],
                ['Obrada poda', 160.0, 1],
                ['Betoniranje poda', 300.0, 1],
                ['Betoniranje vrata', 150.0, 1],
                ['Farbanje ložišta', 30.0, 1],
                ['Farbanje kosine', 20.0, 1],
                ['Pakovanje koncentrične redukcije', 12.5, 1],
                ['Zavarivanje koncentrične redukcije', 13.0, 1],
                ['Obrada koncentrične redukcije', 5.0, 1],
                ['Pakovanje i zavarivanje spirale za čišćenje', 60.0, 1],
                ['Pakovanje kutije otprašivača', 40.0, 1],
                ['Zavarivanje kutije otprašivača', 20.0, 1],
                ['Obrada kutije otprašivača', 5.0, 1],
                ['Pakovanje omotača boce za otprašivanje 24L', 30.0, 1],
                ['Zavarivanje omotača boce za otprašivanje iznutra 24L', 8.0, 1],
                ['Pakovanje danca i omotača (24l)', 24.0, 1],
                ['Pakovanje mufova,nosača tablice I nogara boce za otprašivanje 24L', 46.0, 1],
                ['Zavarivanje mufova,nosača tablice I nogara boce za otprašivanje 24L', 25.0, 1],
                ['Obrada - Čišćenje boce za otprašivanje 24L', 25.0, 1],
                ['Hidro test boce za otprašivanje 24L', 30.0, 1],
                ['Pakovanje I plašta', 950.0, 2],
                ['Zavarivanje I faze I plašta', 45.0, 1],
                ['Zavarivanje cevi na I plaštu', 45.0, 1],
                ['Zavarivanje I plašta (CO2)', 420.0, 1],
                ['Pakovanje II plašta', 700.0, 2],
                ['Zavarivanje II plašta (CO2)', 600.0, 1],
                ['Savijanje krova I plašta (valjcima)', 45.0, 1],
                ['Savijanje krova II plašta (valjcima)', 50.0, 1],
                ['Postavljanje kotla na pod', 30.0, 1],
                ['Kićenje', 420.0, 2],
                ['Pakovanje i zavarivanje dozera (CO2)', 70.0, 1],
                ['Farbanje delova dozera', 45.0, 1],
                ['Kompletiranje dozera', 300.0, 1],
                ['Pakovanje kućišta ciklona', 200.0, 1],
                ['Zavarivanje kućišta ciklona', 200.0, 1],
                ['Pakovanje konusa ciklona', 60.0, 1],
                ['Zavarivanje konusa ciklona', 60.0, 1],
                ['Pakovanje reducira kućišta ventilatora', 10.0, 1],
                ['Pakovanje nastavka multiciklona dužeg', 3.0, 1],
                ['Pakovanje nastavka multiciklona kraćeg', 3.0, 1],
                ['Zavarivanje nastavka dužeg', 3.0, 1],
                ['Zavarivanje nastavka kraćeg', 3.0, 1],
                ['Zavarivanje reducira kućišta ventilatora', 20.0, 1],
                ['Pakovanje kućišta ventilatora', 180.0, 1],
                ['Zavarivanje kućišta ventilatora', 120.0, 1],
                ['Montaža turbine ventilatora i kućišta', 120.0, 1],
                ['Pakovanje ciklon kante za pepeo', 60.0, 1],
                ['Zavarivanje ciklon kante za pepeo', 45.0, 1],
                ['Finalna montaža sklopa ciklona (bez ventilatora)', 280.0, 1],
                ['Pakovanje dimnjače ciklona', 60.0, 1],
                ['Zavarivanje dimnjače ciklona', 60.0, 1],
                ['Obrada ciklon kante ze pepeo', 30.0, 1],
                ['Obrada kućišta ciklona', 40.0, 1],
                ['Pakovanje i varenje oplate (CO2)', 40.0, 1],
                ['Punktovanje pozicija oplate', 4.0, 1],
                ['Brušenje oplate', 30.0, 1],
                ['Kačenje', 5.0, 1],
                ['Plastificiranje', 5.0, 1],
                ['Skidanje sa linije i odlaganje u korpe', 5.0, 1],
                ['Pakovanje kante za pepeo', 15.0, 1],
                ['Brušenje kante za pepeo', 10.0, 1],
                ['Priprema izolacije', 50.0, 1],
                ['Postavljanje izolacije', 60.0, 1],
                ['Priprema oplate za montažu', 50.0, 2],
                ['Montaža elektro ormara i ožičenja na oplatu', 360.0, 1],
                ['Završna montaža oplate i sklopova', 480.0, 2],
                ['Test bezbednosti i funkcionalnosti', 10.0, 1],
                ['Pakovanje i priprema za transport', 45.0, 2],
                ['Pakovanje silosa (priprema za transport)', 30.0, 2],
            ],
        ];

        foreach ($productsData as $fileName => $phases) {
            $nameWithoutExtension = pathinfo($fileName, PATHINFO_FILENAME);

            $product = Product::create([
                'name' => $nameWithoutExtension,
                'code' => 'AUTO-' . strtoupper(substr($nameWithoutExtension, 0, 5)) . '-' . uniqid(),
                'description' => 'Automatski dodat proizvod sa fajla',
                'specifications' => 'Specifikacije nisu unete.',
                'price' => 0.00,
                'status' => 'active',
            ]);

            foreach ($phases as $index => [$phaseName, $timeNorm, $numberOfWorkers]) {
                // Prvo probaj da pronađeš fazu po imenu i time_norm
                $workPhase = WorkPhase::where('name', $phaseName)
                    ->where('time_norm', $timeNorm)
                    ->where('number_of_workers', $numberOfWorkers)
                    ->first();

                // Ako ne postoji, kreiraj novu
                if (!$workPhase) {
                    $workPhase = WorkPhase::create([
                        'name' => $phaseName,
                        'time_norm' => $timeNorm,
                        'location' => 'Seovac',
                        'number_of_workers' => $numberOfWorkers,
                    ]);
                }

                $product->workPhases()->attach($workPhase->id, [
                    'pivot_order' => $index + 1
                ]);
            }
        }
    }
}
