services:
  - type: web
    name: laravel-radijator
    env: docker
    plan: free
    branch: main
    buildFilter:
      paths:
        - Dockerfile
        - render.yaml
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: laravel_db
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: root

databases:
  - name: mysql
    plan: free
